Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

Method 1:
class Solution {
    public char findTheDifference(String s, String t) {
        int[] hash = new int[26];
        for (int i = 0; i < s.length(); i++){
            hash[s.charAt(i) - 'a']++;
        }
        for (int i = 0; i < t.length(); i++){
            hash[t.charAt(i) - 'a']--;
            if (hash[t.charAt(i) - 'a'] < 0){
                return t.charAt(i);
            }
        }
        return '\0';
    }
}

Method 2: Use ASCII code
class Solution {
    public char findTheDifference(String s, String t) {
        int charCode = (int) t.charAt(s.length()); // store the last character of t as ASCII code
        for (int i = 0; i < s.length(); i++){
            charCode -= (int) s.charAt(i);
            charCode += (int) t.charAt(i);
        }
        return (char) (charCode);
    }
}

Method 3: the same concept as single number I
class Solution {
    public char findTheDifference(String s, String t) {
        char c = 0;
        for (int i = 0; i < s.length(); i++){
            c ^= s.charAt(i);
        }
        for (int i = 0; i < t.length(); i++){
            c ^= t.charAt(i);
        }
        return c;
    }
}
